# Generated by Django 5.2.2 on 2025-06-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
